package application.Controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.VBox;

public class AdminPage1Controller implements Initializable{
	@FXML
	private VBox VB_Holder;
	@FXML
	private Label L_greet;
	@FXML
	private Button Bt_Logout;
	@FXML
	private Button Bt_ViewBooking;
	@FXML
	private Button Bt_ViewTimeTable;
	@FXML
	private Button Bt_CancelBooking;
	@FXML
	private Button Bt_BookRoom;
	@FXML
	private Button Bt_RespondToReq;

	@FXML
	public void f_logout(ActionEvent event) {
		// TODO Autogenerated
		Platform.exit();
	}
	
	// Event Listener on Button[#Bt_ViewBooking].onAction
	@FXML
	public void f_viewBookings(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_ViewTimeTable].onAction
	@FXML
	public void f_viewTimeTable(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_CancelBooking].onAction
	@FXML
	public void f_cancelBooking(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_BookRoom].onAction
	@FXML
	public void f_bookRoom(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_RespondToReq].onAction
	@FXML
	public void f_respondToRequests(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		L_greet.setText("Welcome Admin !");
	}
}
