package application.Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

public class BookARoom_StudentController {
	@FXML
	private Button Bt_back;
	@FXML
	private ListView LV_Rooms;
	@FXML
	private Button Bt_SendRequest;

	// Event Listener on Button[#Bt_back].onAction
	@FXML
	public void f_back(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_SendRequest].onAction
	@FXML
	public void f_sendRequest(ActionEvent event) {
		// TODO Autogenerated
	}
}
