package application.Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

public class BookaRoomController {
	@FXML
	private Button Bt_back;
	@FXML
	private ListView LV_RoomList;
	@FXML
	private Button Bt_Book;

	// Event Listener on Button[#Bt_back].onAction
	@FXML
	public void f_back(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_Book].onAction
	@FXML
	public void f_Book(ActionEvent event) {
		// TODO Autogenerated
	}
}
