package application.Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

public class CancelABooking_forStudentController {
	@FXML
	private Button Bt_back;
	@FXML
	private ListView LV_BookingsList;
	@FXML
	private Button Bt_CancelBooking;

	// Event Listener on Button[#Bt_back].onAction
	@FXML
	public void f_back(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_CancelBooking].onAction
	@FXML
	public void f_cancelBooking(ActionEvent event) {
		// TODO Autogenerated
	}
}
