package application.Controllers;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.application.Platform;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class FacultyLoginController implements Initializable {
	@FXML
	private Label L_greet;
	@FXML
	private Button Bt_logout;
	@FXML
	private Button Bt_viewRoomBookings;
	@FXML
	private Button Bt_viewLabel;
	@FXML
	private Button Bt_cancelBooking;
	@FXML
	private Button Bt_bookRoom;

	// Event Listener on Button[#Bt_logout].onAction
	@FXML
	public void f_logout(ActionEvent event) {
		// TODO Autogenerated
		Platform.exit();
	}
	// Event Listener on Button[#Bt_viewRoomBookings].onAction
	@FXML
	public void f_viewRoomBookings(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_viewLabel].onAction
	@FXML
	public void f_viewTimeTable(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_cancelBooking].onAction
	@FXML
	public void f_cancelBooking(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_bookRoom].onAction
	@FXML
	public void f_bookRoom(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		L_greet.setText("Welcome Faculty !");
	}
}
