package application.Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.layout.VBox;

public class LoginController {
	@FXML
	private VBox VB_Holder;
	@FXML
	private TextField Tx_Uname;
	@FXML
	private PasswordField Tx_Passwd;
	@FXML
	private Button Bt_Login;
	@FXML
	private Button Bt_Signup;
	@FXML
	private Label L_Status;

	// Event Listener on Button[#Bt_Login].onAction
	@FXML
	public void f_Login(ActionEvent event) {
		L_Status.setText("Login Pressed");
	}
	// Event Listener on Button[#Bt_Signup].onAction
	@FXML
	public void f_SignUp(ActionEvent event) {
		// TODO Autogenerated
	}
}
