package application.Controllers;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;

import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class LoginController {
	@FXML
	private VBox VB_Holder;
	@FXML
	private TextField Tx_Uname;
	@FXML
	private PasswordField Tx_Passwd;
	@FXML
	private Button Bt_Login;
	@FXML
	private Button Bt_Signup;
	@FXML
	private Label L_Status;

	// Event Listener on Button[#Bt_Login].onAction
	@FXML
	public void f_Login(ActionEvent event) {
		if(Tx_Uname.getText().equals("") || Tx_Passwd.getText().equals("")){
			L_Status.setText("Empty Username or Password");
			return;
		}
		else if(Tx_Uname.getText().equals("student@iiitd.ac.in") && Tx_Passwd.getText().equals("pass")) {
			L_Status.setText("Student Login :)");
			Stage stageTheEventSourceNodeBelongs = (Stage) ((Node)event.getSource()).getScene().getWindow();
		    // OR
		    Stage stageTheLabelBelongs = (Stage) L_Status.getScene().getWindow();
		    // these two of them return the same stage
		    // Swap screen
		    Parent root=null;
			try {
				root = FXMLLoader.load(LoginController.class.getResource("/application/GUIs/StudentLogin.fxml"));
			} catch (IOException e) {
				// TODO Auto-generated catch block
//				System.out.println("NULL         ---");
				e.printStackTrace();
			}
			if(root==null) {
				System.out.println("NULL         +++");
			}
		    stageTheLabelBelongs.setScene(new Scene(root));
		}
		else if(Tx_Uname.getText().equals("faculty@iiitd.ac.in") && Tx_Passwd.getText().equals("pass")) {
			L_Status.setText("Faculty Login :)");
		}
		else if(Tx_Uname.getText().equals("admin@iiitd.ac.in") && Tx_Passwd.getText().equals("pass")) {
			L_Status.setText("Admin Login :)");
		}
		else {
			L_Status.setText("Invalid Username/Password");
		}
	}
	// Event Listener on Button[#Bt_Signup].onAction
	@FXML
	public void f_SignUp(ActionEvent event) {
		// TODO Autogenerated
		L_Status.setText("Opening Sign Up");
	}
}
