package application.Controllers;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;
import javafx.stage.Stage;

public class RespondtoRequestsController {
	@FXML
	private Button Bt_back;
	@FXML
	private Label L_pending;
	@FXML
	private ListView LV_requests;
	@FXML
	private Button Bt_accept;
	@FXML
	private Button Bt_reject;

	// Event Listener on Button[#Bt_back].onAction
	@FXML
	public void f_back(ActionEvent event) {
		// TODO Autogenerated
		Stage stageTheEventSourceNodeBelongs = (Stage) ((Node)event.getSource()).getScene().getWindow();
		Parent root=null;
		try {
			root = FXMLLoader.load(ViewRoomBookingsController.class.getResource("/application/GUIs/AdminPage1.fxml"));
		} catch (IOException e) {
			e.printStackTrace();
			return;
		}
		stageTheEventSourceNodeBelongs.setScene(new Scene(root));
	}
	// Event Listener on Button[#Bt_accept].onAction
	@FXML
	public void f_accept(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_reject].onAction
	@FXML
	public void f_reject(ActionEvent event) {
		// TODO Autogenerated
	}
}
