package application.Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.PasswordField;

public class SignUpController {
	@FXML
	private Button Bt_back;
	@FXML
	private TextField Tx_fName;
	@FXML
	private TextField Tx_lName;
	@FXML
	private TextField Tx_uName;
	@FXML
	private PasswordField Tx_pass;
	@FXML
	private ComboBox CB_userType;
	@FXML
	private Button Bt_submit;

	// Event Listener on Button[#Bt_back].onAction
	@FXML
	public void f_back(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_submit].onAction
	@FXML
	public void f_submit(ActionEvent event) {
		// TODO Autogenerated
	}
}
