package application.Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class StudentLoginController {
	@FXML
	private Button Bt_viewRoomBookings;
	@FXML
	private Button Bt_viewTimeTable;
	@FXML
	private Button Bt_bookRoom;
	@FXML
	private Button Bt_cancelRoom;
	@FXML
	private Button Bt_viewCourses;

	// Event Listener on Button[#Bt_viewRoomBookings].onAction
	@FXML
	public void f_viewRoomBookings(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_viewTimeTable].onAction
	@FXML
	public void f_viewTimeTable(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_bookRoom].onAction
	@FXML
	public void f_bookRoom(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_cancelRoom].onAction
	@FXML
	public void f_cancelRoom(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_viewCourses].onAction
	@FXML
	public void f_viewCourses(ActionEvent event) {
		// TODO Autogenerated
	}
}
