package application.Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.ComboBox;

public class ViewTimeTableController {
	@FXML
	private Button Bt_back;
	@FXML
	private ComboBox CB_select;
	@FXML
	private ListView LV_timeTable;

	// Event Listener on Button[#Bt_back].onAction
	@FXML
	public void f_back(ActionEvent event) {
		// TODO Autogenerated
	}
}
