package application.Controllers.Useless;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.VBox;

public class CourseDetailsController {
	@FXML
	private VBox VB_holder;
	@FXML
	private Button Bt_back;
	@FXML
	private Button Bt_addCourse;
	@FXML
	private Button Bt_logout;
	@FXML
	private Label L_courseNum;
	@FXML
	private TextField Tx_courseNum;
	@FXML
	private Label L_courseName;
	@FXML
	private TextField Tx_courseName;
	@FXML
	private Label L_instructor;
	@FXML
	private TextField Tx_instructor;
	@FXML
	private Label L_pC1;
	@FXML
	private TextField Tx_pC1;
	@FXML
	private Label L_pC2;
	@FXML
	private TextField Tx_pC2;
	@FXML
	private Label L_pC3;
	@FXML
	private TextField Tx_pC3;
	@FXML
	private Label L_pC4;
	@FXML
	private TextField Tx_pC4;
	@FXML
	private Label L_pC5;
	@FXML
	private TextField Tx_pC5;

	// Event Listener on Button[#Bt_back].onAction
	@FXML
	public void f_back(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_addCourse].onAction
	@FXML
	public void f_addCourse(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Bt_logout].onAction
	@FXML
	public void f_logout(ActionEvent event) {
		// TODO Autogenerated
	}
}
